version: '3'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    depends_on:
      - db
    environment:
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${POSTGRES_DB}
    ports:
      - "8080:8080"
    volumes:
      - .:/app 
      - /app/venv  
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]

volumes:
  postgres-data:
